name: Build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 16 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle.kts', 'gradle.properties', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Set Git Identity
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
      - name: Clean Paperweight Cache
        run: ./gradlew cleanCache -Dpaperweight.debug=true

      - name: Apply BenPlane Patches
        run: ./gradlew applyPatches -Dpaperweight.debug=true

      - name: Build Paperclip Jar
        run: ./gradlew paperclipJar -Dpaperweight.debug=true

      - name: Upload Paperclip Jar
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: BenPlane-1.17.1-R0.1-SNAPSHOT.jar
          tag: ${{ github.ref }}
          asset_name: BenPlane.jar
          overwrite: true